#----------------------------------------------
# Regina Gallardo A00815711
# Arturo Moran A00
# cubo semantico
#----------------------------------------------

cuboSemantico = {
# int operacion tipo
    "int": {
    #int operacion int
      "int": {
        "+":"int",
        "-":"int",
        "*":"int",
        "/":"int",
        ">":"bool",
        ">=":"bool",
        "<=":"bool",
        "<":"bool",
        "=":"int",
        "==": "bool",
        "!=":"bool",
        "and":"Error",
        "or":"Error",
        },
    #int operacion float
      "float": {
        "+":"float",
        "-":"float",
        "*":"float",
        "/":"float",
        ">":"bool",
        ">=":"bool",
        "<=":"bool",
        "<":"bool",
        "=":"int",
        "==": "bool",
        "!=":"bool",
        "and":"Error",
        "or":"Error",
        },
    #int operacion string
      "string": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #int operacion bool
      "bool": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #int operacion array
      "array": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
      },
#float operacion tipo
    "float":{
    #float operacion int
      "int": {
        "+":"float",
        "-":"float",
        "*":"float",
        "/":"float",
        ">":"bool",
        ">=":"bool",
        "<=":"bool",
        "<":"bool",
        "=":"float",
        "==": "bool",
        "!=":"bool",
        "and":"Error",
        "or":"Error",
        },
    #float operacion float
      "float": {
        "+":"float",
        "-":"float",
        "*":"float",
        "/":"float",
        ">":"bool",
        ">=":"bool",
        "<=":"bool",
        "<":"bool",
        "=":"float",
        "==": "bool",
        "!=":"bool",
        "and":"Error",
        "or":"Error",
        },
    #float operacion string
      "string": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #float operacion bool
      "bool": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #float operacion array
      "array": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
      },
#string operacion tipo
    "string":{
    #string operacion int
      "int": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #string operacion float
      "float": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #string operacion string
      "string": {
        "+":"string",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"string",
        "==": "bool",
        "!=":"bool",
        "and":"Error",
        "or":"Error",
        },
    #string operacion string
      "bool": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #string operacion array
      "array": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
      },
#bool operacion tipo
    "bool":{
    #bool operacion int
      "int": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #bool operacion float
      "float": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #bool operacion string
      "string": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==":"Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #bool operacion bool
      "bool": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"bool",
        "==":"bool",
        "!=":"bool",
        "and":"bool",
        "or":"bool",
        },
    #bool operacion array
      "array": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
      },
#array operacion tipo
    "array":{
    #array operacion int
      "int": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #array operacion float
      "float": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #array operacion string
      "string": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==":"Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #array operacion bool
      "bool": {
        "+":"Error",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==":"Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
    #array operacion array
      "array": {
        "+":"Array",
        "-":"Error",
        "*":"Error",
        "/":"Error",
        ">":"Error",
        ">=":"Error",
        "<=":"Error",
        "<":"Error",
        "=":"Error",
        "==": "Error",
        "!=":"Error",
        "and":"Error",
        "or":"Error",
        },
      },
    }

prueba = cuboSemantico['int']['int']['+']
print (prueba)
prueba = cuboSemantico['int']['float']['/']
print (prueba)
prueba = cuboSemantico['bool']['int']['+']
print (prueba)
prueba = cuboSemantico['bool']['bool']['and']
print (prueba)
prueba = cuboSemantico['array']['int']['+']
print (prueba)
